### ISSUE TITLE
mlx_compile does not work in C

### ISSUE THREAD

**Issue by edfix** [ml-explore/mlx-c#12]
Here is reproduce  code snippet:
```c
#include <stdio.h>
#include <stdlib.h>

#include "mlx/c/mlx.h"

mlx_array inc_fun(mlx_array in) {
  mlx_array y = mlx_array_from_float(1.0);
  mlx_array res = mlx_add(in, y, MLX_GPU_STREAM);
  mlx_free(y);
  return res;
}

int main() {
  mlx_closure cls = mlx_closure_new_unary(inc_fun);

  // jvp
  {
    mlx_enable_compile();
    printf("start compile:\n");
    mlx_compile(cls, true);
    printf("end compile:\n");
  }

    return 0;
}

```

result: 
libc++abi: terminating due to uncaught exception of type std::invalid_argument: [compile] Cannot compile a non-addressable function.

[this](https://github.com/ml-explore/mlx/blob/main/mlx/compile.cpp#L197) is where it throws exception

**Comment by awni** [comment]
You would need to use this API https://github.com/ml-explore/mlx-c/blob/main/mlx/c/transforms_impl.h#L26-L31 which required you pass a unique address for any compiled function. It does not check that so its undefined if you pass the same address for two functions.

I'd generally warn you about using compile from C. It is easy to break things there.

**Comment by edfix** [comment]
@awni thank you for your reply!
