### ISSUE TITLE
Exception in libc++api

### ISSUE THREAD

**Issue by dcvz** [ml-explore/mlx-c#17]
I'm working on some bindings that make use of `mlx-c` but I'm finding that if I run tests that create arrays right after having previously ran tests i'm getting an error:

```
libc++abi: terminating due to uncaught exception of type std::__1::system_error: condition_variable wait failed: Invalid argument
```

My guess is some kind of threadpool issue, is there a way to specify limits? Could this be an error in `mlx-c`?

**Comment by awni** [comment]
It could be.. could you share a way to reproduce this?

**Comment by dcvz** [comment]
> It could be.. could you share a way to reproduce this?

If you don’t mind checking out a Rust repo, you can check out this branch and run tests via `cargo test`: https://github.com/oxideai/mlx-rs/pull/32

run the tests once which will succeed, then try to immediately run them again and you’ll get this error.

**Comment by dcvz** [comment]
A bit more info here, running the tests consecutively using `-- --test-threads=1` as opposed to all in parallel as rust does, seems to stop the issue. So definitely a thread pool thing it seems.

**Comment by awni** [comment]
Ah. I didn't get you were running tests in parallel. So MLX is not thread safe at the moment. So I would definitely not run the tests in parallel.

Do you need thread safety or is that just a by produce of the default test behavior?

**Comment by dcvz** [comment]
I guess ideally thread safety would be nice, but this was just a product of the default test behaviour. For now I've limited tests to 1 thread and assuming MLX is not thread safe.
