### ISSUE TITLE
[Feature Request] Get device type from `mlx_stream`

### ISSUE THREAD

**Issue by minghuaw** [ml-explore/mlx-c#25]
Because the rust runtime cannot capture c++ exceptions, we are trying to perform checks before crossing the FFI boundary. One thing that the c++ code checks in the `sort` function is whether the device is set to GPU and the array size on the requested axis is larger than 2M. However, the current c wrapper doesn't provide a way to check the device type of a `mlx_stream`. Would it be possible to add this?

**Comment by awni** [comment]
Right, yes we should expose something for you that seems like an oversight.

However the broader point that you cannot capture C++ exceptions is a bit concerning since we use C++ exceptions quite liberally. You would need to reproduce all the error checks which is quite a lot. Is there no workaround for that?

**Comment by minghuaw** [comment]
I don't think it's possible when we use the c wrapper to do ffi.

Technically there's workaround by using the original c++ code with `cxx` crate (https://cxx.rs/), which achieves this by generating and a bunch of c++ files at compile time where the generated wrappers capture exceptions and return a rust error upon exception. This is actually the original approach we took, but it was rather cumbersome to work with (especially with the long compile time due to the files generated at compile time), and we switched to use the `mlx-c` wrapper to do ffi instead.

**Comment by awni** [comment]
Just an update on this after chatting with @andresy. We're considering catching exceptions in the C binding and exposing a way to query for errors / error messages.

@minghuaw  I think such an approach may work better for you than reimplementing all the error checking yourself?

**Comment by minghuaw** [comment]
That'll be great. Id love to help if there's anything that I could contribute to
