### ISSUE TITLE
Failing tests w/ Sequoia

### ISSUE THREAD

**Issue by derekelewis** [ml-explore/mlx-c#30]
`MLXArrayIndexingTests.testSliceWithBroadcast()` & `UpsampleTests.testNearest()` are both failing. Good news is that all other tests pass.

Both are failing with `"vector[] index out of bounds"` at different locations in `collapse_contiguous_dims`.

`testSliceWithBroadcast()`
`utils.h:76`
```
out_strides[j].push_back(st[to_collapse[i - 1]]);
```

`testNearest()`
`utils.h:51`
```
if (st[i] * shape[i] != st[i - 1]) {
```

**Comment by awni** [comment]
We haven't updated MLX for Sequoia yet. I would avoid building for Sequoia until we do a release of MLX core and MLX C which supports 15.0

**Comment by LiYanan2004** [comment]
Same issue here. Is this a bug of the OS or just mlx not adaptable for the new OS?

**Comment by awni** [comment]
> We haven't updated MLX for Sequoia yet. I would avoid building for Sequoia until we do a release of MLX core and MLX C which supports 15.0

**Comment by derekelewis** [comment]
This has been resolved.
