### ISSUE TITLE
Is try catch necessary in `mlx_get_default_device`?

### ISSUE THREAD

**Issue by minghuaw** [ml-explore/mlx-c#43]
It doesn't seem like either `mlx_device_set_()` or `mlx::core::default_device()` would have throw. Is the try catch and returning a status code even necessary in this case?

**Comment by minghuaw** [comment]
The same pattern is observed on a few other functions. For example, `mlx_random_key`

**Comment by andresy** [comment]
Thanks @stemann, that is the point. Also, note that the wrapper functions may allocate memory (e.g. through `mlx_device_set_`, which may call `new`), which may fail.
