### ISSUE TITLE
Bug: `fft`s don't work on gpu

### ISSUE THREAD

**Issue by minghuaw** [ml-explore/mlx-c#45]
There seems to be a bug with all the `fft`s/`ifft`s on gpu with the latest update to mlx 0.20.0

**Comment by minghuaw** [comment]
> Probably you are referring to what was [fixed here](https://github.com/ml-explore/mlx/pull/1566).

This was observed on the current main branch. Is the c binding fetching the wrong version?

**Comment by awni** [comment]
The C bindings [building with MLX 0.20](https://github.com/ml-explore/mlx-c/blob/main/CMakeLists.txt#L37-L38) which does not include that fix. Once we do the next releaase of MLX we can update the tag here.

**Comment by stemann** [comment]
Thus, should be fixed with #46 .
